server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # SPA — redireciona rotas para index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy para API QRNG (Red Pitaya)
    location /api/ {
        proxy_pass http://189.126.105.45:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
