import { createContext, useContext, useState } from "react";

const STORAGE_KEY = "qrng-lang";

// Dicionário PT/EN do site, mesmo padrão do portal Bongo (front/src/context/language).
const translations = {
  pt: {
    // ── Navegação principal (SectionNav) ──
    navKapua: "Kuapoã",
    navVisuals: "Representações Visuais",
    navData: "Dados",
    navApplications: "Aplicações",
    navNist: "Teste NIST",
    navDeveloper: "Desenvolvedor",
    navSettings: "⚙ Configurações",

    // ── HardwareStatusBar ──
    statusOnline: "ONLINE",
    statusOffline: "OFFLINE",
    effectiveOrigin: "origem efetiva",
    notVerified: "(não verificada)",
    buffer: "Buffer",
    generated: "Gerado",
    consumed: "Consumido",
    precollectedRemainingLabel: "Pré-coletado",
    remainingOf: "restantes de",
    sourceUnavailableFallback: "Fonte indisponível — fallback ativo",
    latency: "Latência",
    sourceRemote: "Remota (SP)",
    sourceFpga: "FPGA (Hardware)",
    sourcePrecollected: "Pré-coletado",
    originUnavailable: "indisponível",
    originUnknown: "desconhecida",

    // ── FallbackBanner ──
    fbExhausted: "⚠ BUFFER PRÉ-COLETADO ESGOTADO",
    fbDemoMode: "MODO DEMONSTRAÇÃO — DADOS PRÉ-COLETADOS",
    fbBytesRemaining: "bytes restantes",
    fbAlmostExhausted: " (quase esgotado)",
    fbProvenance: "Proveniência",
    fbNotRegistered: "não registrada",
    fbNotLiveMeasure: "— não é uma medida ao vivo do hardware",
    fbKeyGenBlocked: "Geração de chaves/seed operacional bloqueada nesta fonte",
    fbReuseWarningPrefix: "Isso reaproveita os mesmos",
    fbReuseWarningSuffix: "bytes desde o início — não gera uma amostra nova.",
    fbConfirmRestart: "Confirmar reinício",
    fbCancel: "Cancelar",
    fbRestartDemo: "Reiniciar demonstração",

    // ── Footer ──
    footerConnectedTitle: "Conectado ao hardware:",
    footerConnectedPrefix: "Os dados QRNG nesta demo vêm diretamente da fonte",
    footerConnectedSuffix: "A entropia é gerada por medições de fenômenos quânticos reais, não por algoritmos determinísticos.",
    footerOfflineTitle: "Modo offline:",
    footerOfflinePrefix: "O backend QRNG está indisponível. Os dados QRNG exibidos são de uma",
    footerSamplePrecollected: "amostra pré-coletada",
    footerOfflineSuffix: "(10.000 bytes do Red Pitaya). Embora sejam dados quânticos genúinos, não estão sendo gerados em tempo real. Conecte ao backend para dados ao vivo.",
    footerDevelopedBy: "Desenvolvido por DOBSLIT",

    // ── KapuaSection (página inicial) ──
    kc0Name: "Fonte de Entropia Quântica",
    kc0Desc: "A origem da aleatoriedade vem de um processo físico quântico. O sinal capturado carrega flutuações imprevisíveis que não são geradas por algoritmo determinístico.",
    kc0Badge: "Entropia física",
    kc1Name: "Conversão Analógico-Digital",
    kc1Desc: "O sinal físico é convertido para dados digitais por um estágio de aquisição. Essa etapa transforma o ruído quântico em amostras digitais que podem ser processadas.",
    kc1Badge: "Amostragem",
    kc2Name: "FPGA / Processamento em Hardware",
    kc2Desc: "A FPGA realiza a captura e o processamento inicial dos dados, permitindo baixa latência e fluxo contínuo de bytes aleatórios.",
    kc2Badge: "Hardware",
    kc3Name: "Extração de Entropia",
    kc3Desc: "O pós-processamento remove vieses e organiza os bits para produzir uma sequência adequada para aplicações criptográficas, simulações e testes estatísticos.",
    kc3Badge: "Pós-processamento",
    kc4Name: "Buffer de Dados",
    kc4Desc: "Os bytes gerados são armazenados em um buffer para consumo pelas aplicações, APIs e interfaces do sistema.",
    kc4Badge: "Buffer",
    kc5Name: "API QRNG",
    kc5Desc: "A API disponibiliza os dados aleatórios para aplicações externas, download, geração de chaves, sorteios, simulações e testes.",
    kc5Badge: "Integração",
    kc6Name: "Validação Estatística",
    kc6Desc: "O sistema pode executar análises estatísticas e testes NIST para avaliar a qualidade dos dados gerados.",
    kc6Badge: "Teste NIST",
    kc7Name: "Aplicações",
    kc7Desc: "Os números aleatórios podem ser usados em criptografia, autenticação, Monte Carlo, IA, otimização, jogos, educação e pesquisa.",
    kc7Badge: "Uso prático",
    kf0Title: "Fonte QRNG / FPGA",
    kf0Desc: "Entropia gerada por fenômenos quânticos em hardware FPGA dedicado.",
    kf1Title: "Entropia Física",
    kf1Desc: "Aleatoriedade fundamentalmente imprevisível, não algoritmos.",
    kf2Title: "Geração de Números",
    kf2Desc: "Números e bytes aleatórios com distribuição uniforme comprovada.",
    kf3Title: "Download de Dados Brutos",
    kf3Desc: "Exporte bytes quânticos para uso em simulações, pesquisa e análise.",
    kf4Title: "Testes Estatísticos NIST",
    kf4Desc: "Validação de entropia via suíte SP 800-90B com resultados detalhados.",
    kapuaStepLabel: "Etapa",
    kapuaOfLabel: "de",
    kapuaPrev: "◀ Anterior",
    kapuaNext: "Próximo ▶",
    kapuaStopFlow: "⏹ Parar",
    kapuaPlayFlow: "▶ Ver fluxo completo",
    kapuaStatusOnline: "● ONLINE",
    kapuaStatusChecking: "○ VERIFICANDO",
    kapuaStatusFallback: "◐ FALLBACK",
    kapuaStatusDegraded: "◐ DEGRADADO",
    kapuaStatusOffline: "○ OFFLINE",
    kapuaSourceDefault: "Kuapoã QRNG",
    kapuaSourceFpga: "FPGA/Hardware",
    kapuaSourceFallbackInternal: "Fallback interno",
    kapuaSubtitle: "Gerador Quântico de Números Aleatórios",
    kapuaDescP: "O Kuapoã é o sistema de geração de números aleatórios quânticos da Dobslit. Ele utiliza uma fonte física quântica, aquisição em hardware e processamento dedicado para gerar entropia real para criptografia, simulações, autenticação, pesquisa e testes estatísticos.",
    kapuaGenerating: "⏳ Gerando...",
    kapuaGenerateBtn: "🎲 Gerar número aleatório",
    kapuaDownloading: "⬇ Baixando...",
    kapuaDownloadBtn: "⬇ Baixar dados QRNG",
    kapuaExploreBtn: "🔍 Explorar componentes",
    kapuaRandomNumberLabel: "NÚMERO ALEATÓRIO · Fonte:",
    kapuaDlErrorPrecollected: "Fonte pré-coletada tem apenas 10.000 bytes. Use a aba Dados para exportar até 10 KB, ou selecione Remote / FPGA para o download de 1 MiB.",
    kapuaDlErrorOffline: "Backend QRNG offline ou indisponível. Acesse a aba Dados para mais opções.",
    kapuaExploreLabel: "EXPLORAR:",
    kapuaNavDataQrng: "Dados QRNG",
    kapuaSvgNistLabel: "Testes NIST",
    kapuaSvgAppsLabel: "Aplicações",

    // ── DataPipeline / StatsBadges (games) ──
    dpNoiseQ: "Ruido Q.",
    dpEsteDemo: "Este Demo",
    dpFotons: "Fotons",
    dpOffline: "offline",
    dpSource: "Fonte",
    statsEntropy: "Entropia",

    // ── QuantumVisualizer ──
    qvGalaxy: "Galaxia",
    qvMandala: "Mandala",
    qvCracker: "LCG Cracker",
    qvMtClone: "MT19937 Clone",
    qvSonification: "Sonificação",
    qvMathRandomExhausted: "Math.random() — pré-coletado esgotado",
    qvMathRandomNetError: "Math.random() — erro de rede",
    qvAboutExperiment: "Sobre este experimento",
    qvSpeed: "Velocidade",
    qvDisableSound: "Desativar som",
    qvEnableSound: "Ativar som",
    qvVolume: "Volume",
    qvEnablePrng: "Ativar PRNG",
    qvMutePrng: "Mutar PRNG",
    qvEnableQrng: "Ativar QRNG",
    qvMuteQrng: "Mutar QRNG",
    qvReset: "Reiniciar",
    qvBytes: "bytes",
    qvFps: "fps",

    // ── Canvas labels (visualizations/*.js) ──
    vzCoverage: "Cobertura",
    vzCollectingOutputs: "COLETANDO SAIDAS",
    vzInternalState: "ESTADO INTERNO (624 PALAVRAS DE 32 BITS)",
    vzCloned: "CLONADO!",
    vzPrediction: "PREDICAO",
    vzMt19937Cloned: "MT19937 CLONADO",
    vzCloneFailed: "CLONE FALHOU",
    vzExperimentDone: "EXPERIMENTO CONCLUIDO",
    vzAccuracy: "ACURACIA",
    vzCorrectPredictions: "predicoes corretas",
    vzObservation: "OBSERVACAO",
    vzBreakingLcg: "QUEBRANDO O LCG...",
    vzRealtimePrediction: "PREDICAO EM TEMPO REAL",
    vzPhase: "FASE",
    vzLcgCracked: "LCG QUEBRADO",
    vzUnpredictable: "IMPREVISIVEL",
    vzSonificationTitle: "SONIFICACAO — ESCALA PENTATONICA",

    // ── AnalysisSection ──
    asSamples: "Amostras",
    asGenerating: "Gerando...",
    asGenerate: "Gerar",
    asDistribution: "Distribuição",
    asBits64: "Bits (64 amostras)",

    // ── StreamPanel ──
    spParticles: "Partículas",
    spStop: "Parar",
    spStart: "Iniciar Stream",
    spUnknownError: "Erro desconhecido",
    spReadyRealtime: "Pronto para visualizar bytes quanticos em tempo real",
    spUnavailablePrecollected: "Stream indisponivel com dados pre-coletados",
    spBackendOfflineStream: "Backend offline — stream indisponivel",
    spWaitingHardware: "Aguardando dados do hardware QRNG...",
    spDisconnected: "Desconectado",
    spReconnect: "Reconectar",
    spClickToStart: "Clique em \"Iniciar Stream\" para visualizar",
    spNoStreamPrecollected: "Sem stream no modo pre-coletado",
    spBackendOffline: "Backend offline",

    // ── VisuaisSection (sub-tabs) ──
    visTabInteractive: "Visualizações Interativas",
    visTabAnalysis: "Análise Estatística",

    // ── DataSection ──
    dsSourceTitle: "Fonte QRNG",
    dsPrecollectedActivePrefix: "Fonte pré-coletada ativa.",
    dsPrecollectedActiveSuffix: "bytes QRNG reais disponíveis localmente.",
    dsDegradedWaiting: "Backend conectado, mas buffer de entropia vazio. Aguarde recarga do FPGA...",
    dsOnlineReady: "Backend QRNG online. Dados prontos para exportação.",
    dsOfflineMsg: "Backend QRNG offline. Não é possível gerar dados reais agora.",
    dsLatency: "latência",
    dsSourceLabel: "fonte",
    dsBuffer: "buffer",
    dsExportModeTitle: "Modo de Exportação",
    dsModeRaw: "Raw Binário",
    dsModeHex: "Hexadecimal",
    dsModeUint8: "Decimal / uint8",
    dsModeRange: "Faixa Personalizada",
    dsModeMontecarlo: "Monte Carlo",
    dsDescRaw: "Exporta bytes QRNG brutos (.bin). Cada byte tem 8 bits de largura; a min-entropia real por byte é estimada pela suíte NIST SP 800-90B (aba Teste NIST), não é assumida automaticamente.",
    dsDescHex: "Converte os bytes QRNG para representação hexadecimal. Útil para criptografia e depuração.",
    dsDescUint8: "Exporta cada byte como inteiro 0–255 (uint8). Prático para ML, datasets e análise estatística.",
    dsDescRange: "Gera inteiros em intervalo [min, max] arbitrário. Usa rejection sampling (uint32) para eliminar viés.",
    dsDescMontecarlo: "Gera floats em [0, 1) a partir de uint32 QRNG ÷ 2³². Resolução ≈ 2.3×10⁻¹⁰. Ideal para simulações.",
    dsConfigTitle: "Configurações",
    dsSize: "Tamanho:",
    dsCustomBytes: "Personalizado (bytes):",
    dsSeparator: "Separador:",
    dsBytesPerLine: "Bytes por linha:",
    dsFile: "Arquivo:",
    dsMin: "Mínimo:",
    dsMax: "Máximo:",
    dsQuantity: "Quantidade:",
    dsApply: "Aplicar",
    dsRawFileInfo: "Formato binário puro (.bin). Arquivo de {size} = {bytes} bytes.",
    dsSepContinuous: "contínuo",
    dsSepSpaces: "espaços",
    dsSepPerLine: "por linha",
    dsHexInfoArrow: "chars hex",
    dsHexInfoSpaces: "espaços",
    dsUint8Info: "números inteiros no intervalo 0–255, gerados de bytes QRNG brutos.",
    dsAllowRepeats: "Permitir repetição",
    dsSortResult: "Ordenar resultado",
    dsRangeInvalidCount: "Quantidade inválida para modo sem repetição: intervalo [{min}–{max}] tem apenas {n} valores.",
    dsRangeGeneratesPrefix: "Gera",
    dsRangeGeneratesMid: "número(s) no intervalo",
    dsRangeGeneratesSuffix: "Faixa: {n} valores.",
    dsRangeFloyd: "Algoritmo de Floyd F2 (sem repetição, sem viés).",
    dsRangeRejection: "Rejection sampling uint32 (sem viés).",
    dsMcInfo: "Cada uint32 QRNG é mapeado para [0, 1) via n÷2³². Precisão de 15 casas decimais. Consome {n} bytes QRNG.",
    dsQuickAppsTitle: "Aplicações Rápidas",
    dsPreset0Label: "Byte Array",
    dsPreset0Desc: "uint8 · 0–255 · 1 KB",
    dsPreset1Label: "Loteria 6/60",
    dsPreset1Desc: "6 num · 1–60 · sem rep.",
    dsPreset2Label: "Dado (1d6)",
    dsPreset2Desc: "1 número · 1–6",
    dsPreset3Label: "Monte Carlo",
    dsPreset3Desc: "1000 floats · [0, 1)",
    dsPreset4Label: "IA / Dataset",
    dsPreset4Desc: "uint8 · 4 KB · JSON",
    dsPreset5Label: "Sorteio IDs",
    dsPreset5Desc: "sem rep. · faixa livre",
    dsPreviewTitle: "Prévia e Download",
    dsGeneratingBtn: "⏳ Gerando...",
    dsGeneratePreviewBtn: "Gerar prévia",
    dsDownloadBtn: "↓ Baixar arquivo",
    dsCopiedBtn: "✓ Copiado!",
    dsCopyBtn: "Copiar",
    dsClearBtn: "Limpar",
    dsPreviewFirst32Hex: "Primeiros 32 bytes (hex):",
    dsPreviewFirst64: "Primeiros 64 bytes (sep: {sep}):",
    dsPreviewFirst32Of: "Primeiros 32 de {n} valores:",
    dsPreviewNumbersGenerated: "{n} número(s) gerado(s) [{min}–{max}]:",
    dsPreviewMcPoints: "{n} pontos Monte Carlo [0, 1):",
    dsStatMin: "mín",
    dsStatMax: "máx",
    dsStatMean: "média",
    dsStatBytesQrng: "bytes QRNG",
    dsLatencyApi: "latência API",
    dsFileLabel: "arquivo",
    dsSuccessMsg: "✓ Arquivo gerado com sucesso usando entropia QRNG real.",
    dsConsumedBytes: "Foram consumidos {n} bytes QRNG.",
    dsIdleHintPrefix: "Configure o modo acima e clique em",
    dsIdleHintSuffix: "para visualizar e baixar dados QRNG.",
    dsValidatePrecollectedExceeded: "Fonte pré-coletada: restam apenas {remaining} de {total} bytes nesta sessão. Reduza o tamanho/quantidade, use \"Reiniciar demonstração\" no banner acima, ou troque para uma fonte QRNG ao vivo.",
    dsValidateInvalidSize: "Tamanho inválido. Use entre 1 e {max}.",
    dsValidateRangeInvalid: "Intervalo inválido: o valor máximo deve ser ≥ ao mínimo.",
    dsValidateMinQty: "Quantidade deve ser ao menos 1.",
    dsValidateMaxQty: "Quantidade máxima é 100 000.",
    dsValidateNoRepeatInvalid: "Quantidade inválida para modo sem repetição: intervalo [{min}–{max}] tem apenas {n} valores distintos.",
    dsValidateMcQty: "Quantidade deve ser entre 1 e 100 000.",
    dsGenerateError: "Erro ao gerar dados QRNG. Verifique sua conexão.",
    dsInsufficientBuffer: "Buffer QRNG insuficiente. Tente reduzir a quantidade.",

    // ── ApplicationsSection ──
    apSourceBadgeDefault: "⚛ Kuapoã QRNG",
    apFunctional: "Funcional",
    apCopied: "Copiado!",
    apCopy: "Copiar",
    apReqId: "id",
    apOperationalDisabled: "GERAÇÃO OPERACIONAL DESABILITADA — validação estatística da fonte (restart campaign, health tests SP 800-90B) ainda pendente.",
    apKeyTitle: "🔑 Gerar Chave Quântica",
    apKeyDesc: "Gere chaves e sementes criptográficas a partir de entropia física fornecida pelo Kuapoã.",
    apGenerating: "Gerando...",
    apKeyGenerateBtn: "Gerar chave quântica",
    apKeyBlockedMsg: "Geração operacional de chaves temporariamente desabilitada — a fonte QRNG ainda está em validação estatística (restart campaign e health tests SP 800-90B pendentes). Ver documentação técnica.",
    apKeyPlaceholder: "Selecione o tamanho e clique em Gerar...",
    apSeedTitle: "🧠 Seed Quântica para IA",
    apSeedDesc: "Modelos de IA usam aleatoriedade em inicialização de pesos, divisão de datasets e experimentos. O Kuapoã fornece seeds baseadas em entropia física para experimentos mais robustos e reproduzíveis.",
    apSeedGenerateBtn: "Gerar seed para IA",
    apSeedBlockedMsg: "Geração operacional de seed temporariamente desabilitada — a fonte QRNG ainda está em validação estatística (restart campaign e health tests SP 800-90B pendentes). Ver documentação técnica.",
    apSeedUint32Label: "SEED UINT32",
    apSeedUint64Label: "SEED UINT64",
    apUsageExamples: "EXEMPLOS DE USO",
    apCopyUint32: "Copiar uint32",
    apCopyUint64: "Copiar uint64",
    apMcTitle: "π Monte Carlo Quântico",
    apMcDesc: "Estime π usando pontos gerados por entropia quântica e visualize o comportamento estatístico da amostragem. Cada ponto usa 8 bytes do Kuapoã.",
    apMcCalculating: "Calculando...",
    apMcEstimateBtn: "Estimar π com {n} pontos",
    apMcRealPi: "π real",
    apMcErrorLabel: "Erro",
    apMcInsideTotal: "{inside} dentro / {total} total",
    apRaffleMinParticipants: "Insira pelo menos 2 participantes.",
    apRaffleTitle: "🎫 Sorteio Auditável",
    apRaffleDesc: "Realize sorteios auditáveis usando bytes QRNG, com registro de timestamp, fonte e comprovante. Usa rejection sampling para evitar viés de módulo.",
    apRaffleSortingBtn: "Sorteando...",
    apRaffleDrawBtn: "Sortear",
    apWinnerLabel: "VENCEDOR",
    apRaffleRankOf: "#{idx} de {total} participantes",
    apVoucherLabel: "COMPROVANTE",
    apCopyVoucher: "Copiar comprovante",
    apVoucherTemplate: "Sorteio Kuapoã/Dobslit | Vencedor: {winner} | Participantes: {total} | Timestamp: {ts} | Source: {source} | Bytes: {bytes}... | Req: {req}",
    apGamesTitle: "🎲 Jogos e Educação",
    apGamesDesc: "Experimente moeda e dado alimentados por entropia quântica. Cada resultado usa bytes do Kuapoã/backend.",
    apCoinTitle: "Moeda Quântica",
    apHeads: "CARA",
    apTails: "COROA",
    apFlipCoinBtn: "Lançar moeda",
    apDiceTitle: "Dado Quântico",
    apRollDiceBtn: "Lançar dado",
    apWalkTitle: "🚶 Random Walk Quântico",
    apWalkDesc: "Cada passo usa 2 bits do Kuapoã: 00=cima, 01=baixo, 10=esquerda, 11=direita. Verde = início · Vermelho = posição final.",
    apStepsWord: "passos",
    apWalkingBtn: "Caminhando...",
    apStartWalkBtn: "Iniciar walk ({steps} passos)",
    apFinalPosition: "Posição final",
    apOptimTitle: "📈 Otimização Estocástica",
    apOptimDesc: "Algoritmos de otimização estocástica dependem de boas fontes de aleatoriedade. Aqui buscamos o máximo de f(x) = sin(x) + cos(2x) em [0, 2π] por amostragem quântica aleatória.",
    apSamplesWord: "amostras",
    apOptimizingBtn: "Otimizando...",
    apFindMaxBtn: "Buscar máximo com {n} amostras QRNG",
    apOptimalX: "x ótimo (rad)",
    apMaxFx: "f(x) máximo",
    apBestSampleNum: "Melhor amostra #",
    apMainTitle: "Aplicações Kuapoã",
    apMainDesc: "Explore demonstrações práticas da aleatoriedade quântica do Kuapoã. Todas as aplicações usam bytes fornecidos pelo QRNG/backend da Dobslit — incluindo o fallback interno quando a FPGA não estiver disponível. Nenhuma aplicação usa serviços externos de aleatoriedade.",
    apDemosCount: "7 demos",
    apNoExternalServices: "Sem serviços externos",

    // ── NISTSection ──
    nistPassed: "Passou",
    nistFailed: "Falhou",
    nistOriginPeriodicLive: "Medida periódica da fonte ao vivo",
    nistOriginLive: "Captura ao vivo",
    nistOriginHistorical: "Arquivo histórico",
    nistOriginUpload: "Upload manual",
    nistOriginUnknown: "Desconhecida",
    nistSyntheticTag: "SINTÉTICO",
    nistTestBoth: "IID + não-IID",
    nistTestIidOnly: "Apenas IID",
    nistTestNonIidOnly: "Apenas não-IID",
    nistFmtAuto: "Auto (detectar)",
    nistFmtRaw: "Raw/binário (.bin)",
    nistFmtU32txt: "uint32 texto (.txt)",
    nistFmtBits: "Bits 0/1 (.txt)",
    nistJobTitle: "Job NIST",
    nistTabSummary: "Resumo",
    nistTabEstimators: "Estimadores",
    nistTabFullLog: "Log completo",
    nistFileSection: "ARQUIVO",
    nistOriginalName: "Nome original",
    nistTestTypeLabel: "Tipo de teste",
    nistFormatLabel: "Formato",
    nistTriggerLabel: "Trigger",
    nistDurationLabel: "Duração",
    nistSha256Label: "SHA-256 original",
    nistIidLabel: "IID",
    nistNonIidLabel: "NÃO-IID",
    nistHOriginalSymbol: "H_original (por símbolo de 8 bits)",
    nistLimitingEstimatorOriginal: "↳ estimador limitante (original)",
    nistHBitstringBit: "H_bitstring (por bit)",
    nistLimitingEstimatorBitstring: "↳ estimador limitante (bitstring)",
    nistBitstringConversion: "conversão bitstring→símbolo",
    nistHMinNonIid: "h_min_non_iid = min(H_original, 8×H_bitstring)",
    nistLimitingPath: "trilha que limita",
    nistLimitingEstimator: "estimador limitante (corresponde a h_min)",
    nistIidFailedWarningPrefix: "⚠ Hipótese IID falhou → o crédito de entropia é",
    nistIidFailedWarningSuffix: "bits/símbolo de 8 bits). h_min_iid NÃO é usado.",
    nistParseIncomplete: "⚠ Saída do assessment incompleta — algum campo essencial não pôde ser extraído.",
    nistTrackOriginal: "TRILHA ORIGINAL (por símbolo de 8 bits)",
    nistTrackBitstring: "TRILHA BITSTRING (por bit)",
    nistBitsPerSymbol: "bits/símbolo",
    nistBitsPerBit: "bits/bit",
    nistLimits: "◀ limita",
    nistAwaitingCompletion: "Aguardando conclusão...",
    nistLogNotAvailable: "Log ainda não disponível.",
    nistLoadingLog: "Carregando log...",
    nistServiceDownMsg: "⚠ Serviço NIST não acessível. Verifique se qrng-nist-api está rodando na VM de Recife.",
    nistSyntheticBanner: "RESULTADO SINTÉTICO DE STAGING — NÃO É UM ASSESSMENT SP 800-90B",
    nistSyntheticBannerPrefix: "Motor:",
    nistSyntheticBannerSuffix: "Os campos IID / non-IID / min-H abaixo são valores sintéticos determinísticos para testar parsing e interface — não representam avaliação estatística de entropia e não constituem conformidade NIST.",
    nistIntegration: "Integração",
    nistEnabled: "Habilitada",
    nistDisabled: "Desabilitada",
    nistEngine: "Motor",
    nistNextAuto: "Próx. automático",
    nistNextAutoDisabled: "desativado (sem captura live)",
    nistInterval: "Intervalo",
    nistQueue: "Fila",
    nistJobsWord: "job(s)",
    nistLiveCaptureUnavailablePrefix: "ℹ Captura live indisponível — nenhum mecanismo de captura ao vivo controlada está configurado. Nenhuma execução periódica é agendada",
    nistLiveCaptureUnavailableSuffix: "o job periódico não reavalia nenhum arquivo automaticamente. Resultados abaixo (se houver) vêm de upload manual ou execução avulsa sobre um arquivo específico.",
    nistLastResult: "ÚLTIMO RESULTADO",
    nistOriginPrefix: "Origem:",
    nistOriginPeriodicDetail: "Medida periódica da fonte ao vivo — veja \"Idade da amostra\" para saber há quanto tempo foi capturada.",
    nistOriginSpecificDetail: "Avaliação de uma amostra específica, não uma medida contínua da saúde atual do stream ao vivo.",
    nistStaleWarningPrefix: "⚠ AMOSTRA DESATUALIZADA — capturada há",
    nistStaleWarningMid: "mais que o intervalo entre execuções periódicas",
    nistStaleWarningSuffix: "Este resultado não reflete o estado atual da fonte ao vivo.",
    nistStatusLabel: "Status",
    nistMinHLabel: "min-H non-IID",
    nistFileLabel: "Arquivo",
    nistSubmittedAt: "Enviado em",
    nistSampleAge: "Idade da amostra",
    nistTransportOrigin: "Transporte / origem física",
    nistEvaluatedSymbol: "Símbolo avaliado pelo NIST",
    nistPerWord: "palavra",
    nistConditioned: "condicionado",
    nistNotConditioned: "sem conditioning",
    nistRunNowTitle: "Executar teste agora",
    nistRunNowDescPrefix: "Testa o arquivo mais recente em",
    nistRunNowDescSuffix: "(≥ 1 MB).",
    nistCreatingJob: "Criando job...",
    nistAwaitingJob: "Aguardando job...",
    nistRunNowBtn: "▶ Executar teste agora",
    nistJobRunningPrefix: "● Job",
    nistJobRunningSuffix: "em execução...",
    nistUploadTitle: "Upload + teste",
    nistUploadDescPrefix: "Envie um arquivo",
    nistUploadDescSuffix: "Mínimo 1 MB.",
    nistSending: "Enviando...",
    nistUploadBtn: "⬆ Enviar e testar",
    nistJobHistory: "Histórico de jobs",
    nistRefreshBtn: "↺ Atualizar",
    nistNoJobs: "Nenhum job registrado ainda.",
    nistThDate: "Data/hora",
    nistThTrigger: "Trigger",
    nistThFile: "Arquivo",
    nistThTest: "Teste",
    nistThStatus: "Status",
    nistThIid: "IID",
    nistThMinH: "min-H non-IID",
    nistThDuration: "Duração",
    nistViewBtn: "Ver",
    nistDaysWord: "dias",
    nistCreateJobError: "Erro ao criar job",
    nistUploadError: "Erro no upload",

    // ── DeveloperPage / DocsCard ──
    devEndpointsAvailable: "Endpoints disponíveis",
    devEpRandomDesc: "Bytes aleatórios (máx. 1 MiB)",
    devEpHealthDesc: "Status do QRNG upstream",
    devEpTokenDesc: "Informações do seu token",
    devEpUsageDesc: "Estatísticas de uso",
    devEpRequestsDesc: "Histórico de chamadas",
    devEpRotateDesc: "Regenerar token",
    devEpRevokeDesc: "Revogar token",
    devExRandomHex: "Gerar bytes aleatórios (hex)",
    devExRandomBase64: "Gerar bytes aleatórios (base64)",
    devExHealth: "Status do QRNG",
    devExUsage: "Consultar uso do token",
    devUsageExamplesTitle: "Exemplos de uso",
    devAuthTitle: "Autenticação:",
    devAuthDescPrefix: "Chamadas machine-to-machine usam o header",
    devAuthDescSuffix: "O token de API não expira, mas pode ser regenerado ou revogado na aba Token.",
    devTokenLoadError: "Não foi possível carregar informações do token.",
    devTokenServerDown: "Servidor de tokens indisponível.",
    devTabUsage: "Uso",
    devTabCalls: "Chamadas",
    devCheckingSession: "Verificando sessão...",
    devAreaTitle: "QRNG API — Área do Desenvolvedor",
    devFpgaOnline: "● FPGA Online",
    devFpgaOffline: "● FPGA Offline",
    devFpgaChecking: "● FPGA …",
    devUptime24h: "Uptime 24h",
    devLogout: "Sair",
    devQuotaCritical: "Cota quase esgotada — {n}/{m} req hoje ({pct}%). Resetará à meia-noite UTC.",
    devQuotaWarning: "Atenção: {pct}% da cota diária utilizada ({n}/{m} req).",
    devLoadingGeneric: "Carregando...",
    devLoadingStats: "Carregando estatísticas...",
    devLoadingCalls: "Carregando chamadas...",
    devGenerateTokenFirst: "Gere um token primeiro na aba Token.",

    // ── AuthPage ──
    authPasswordMismatch: "As senhas não coincidem.",
    authPasswordTooShort: "A senha deve ter pelo menos 8 caracteres.",
    authInvalidCredentials: "E-mail ou senha incorretos.",
    authEmailTaken: "Este e-mail já está cadastrado.",
    authMissingFields: "Preencha e-mail e senha.",
    authUnknownError: "Erro desconhecido.",
    authConnectionError: "Não foi possível conectar ao servidor.",
    authLoginPrompt: "Faça login para acessar seu token e os logs de uso.",
    authRegisterPrompt: "Crie uma conta para obter acesso à API de aleatoriedade quântica.",
    authLogin: "Entrar",
    authCreateAccount: "Criar conta",
    authEmailPlaceholder: "E-mail",
    authPasswordPlaceholder: "Senha",
    authConfirmPasswordPlaceholder: "Confirmar senha",
    authWait: "Aguarde...",
    authNoAccount: "Sem conta?",
    authSignUp: "Cadastre-se",

    // ── TokenCard ──
    tcMyApiToken: "Meu Token de API",
    tcActive: "● Ativo",
    tcRevoked: "● Revogado",
    tcSaveNowWarning: "Guarde seu token agora — ele não será exibido novamente após sair desta página.",
    tcGenerateTitle: "Gere seu token de acesso",
    tcGenerateDescPrefix: "Cada conta tem um token único de acesso à API. Use-o no header",
    tcGenerateDescSuffix: "em todas as chamadas.",
    tcQuota: "1 000 req/dia",
    tcQuotaDesc: "Cota diária para chamadas autenticadas",
    tcMaxSize: "Até 1 MiB por req",
    tcMaxSizeDesc: "1 048 576 bytes — formatos hex, base64 ou uint8",
    tcPermanentToken: "Token permanente",
    tcPermanentTokenDesc: "Não expira; pode ser regenerado ou revogado a qualquer momento",
    tcLogsStats: "Logs e estatísticas",
    tcLogsStatsDesc: "Histórico completo de chamadas e uso agregado",
    tcGenerating: "Gerando...",
    tcGenerateBtn: "Gerar Token",
    tcHide: "Ocultar",
    tcShow: "Mostrar",
    tcRegenerating: "Aguarde...",
    tcRegenerateBtn: "Regenerar",
    tcRevokeBtn: "Revogar",
    tcGenerateNewBtn: "Gerar Novo Token",
    tcCreatedAt: "Criado",
    tcLastUsedAt: "Último uso",
    tcName: "Nome",
    tcCreateError: "Erro ao criar token.",
    tcRotateError: "Erro ao regenerar token.",
    tcRevokeError: "Erro ao revogar token.",
    tcConnectionError: "Não foi possível conectar ao servidor.",
    tcRotateConfirm: "Regenerar o token irá invalidar o token atual. Continuar?",
    tcRevokeConfirm: "Revogar o token irá desativar permanentemente o acesso. Continuar?",

    // ── UsageCard ──
    ucTitle: "Uso do Token",
    ucRequestsToday: "Requests hoje",
    ucBytesToday: "Bytes hoje",
    ucRequests7d: "Requests 7d",
    ucRequests30d: "Requests 30d",
    ucDailyQuotaRequests: "Cota diária — requests",
    ucDailyQuotaBytes: "Cota diária — bytes",
    ucRemainingToday: "restantes hoje",
    ucLimitPerReq: "Limite por req",
    ucRemainingTodayFull: "Restam hoje",
    ucLastUsedAt: "Último uso",

    // ── RequestLogsTable ──
    rltRecentCalls: "Chamadas Recentes",
    rltNoCallsYet: "Nenhuma chamada registrada ainda.",
    rltExporting: "Exportando...",
    rltExportCsv: "Exportar CSV",
    rltFormat: "formato",
    rltTime: "tempo",
    rltDate: "data",

    // ── AdminPage ──
    adminPanelTitle: "Painel Admin",
    adminRefresh: "Atualizar",
    adminTabTokens: "Tokens",
    adminTabUsers: "Usuários",
    adminThEmail: "e-mail",
    adminThQuotaDay: "cota/dia",
    adminThReqToday: "req hoje",
    adminThCreated: "criado",
    adminThActions: "ações",
    adminNoTokens: "Nenhum token encontrado.",
    adminRevokeTokenConfirm: "Revogar este token?",
    adminThRole: "papel",
    adminThRegisteredAt: "cadastrado em",
    adminNoUsers: "Nenhum usuário encontrado.",

    // ── NotebookPage ──
    nbEpRandom: "GET /v1/random — Bytes aleatórios",
    nbEpHealth: "GET /v1/health — Status do QRNG",
    nbEpMeToken: "GET /v1/me/token — Informações do token",
    nbEpMeUsage: "GET /v1/me/usage — Estatísticas de uso",
    nbEpMeRequests: "GET /v1/me/requests — Histórico de chamadas",
    nbParamFormat: "Formato",
    nbParamLimit: "Limite",
    nbRunning: "Executando...",
    nbErrorMs: "Erro",
    nbNotExecuted: "Não executado",
    nbCopyAsCurl: "Copiar como curl",
    nbRunBtn: "▶ Run",
    nbRemoveCellTitle: "Remover célula",
    nbPressRunToExecute: "Pressione ▶ Run para executar",
    nbTokenLabel: "Token:",
    nbTokenPlaceholder: "dobslit_qrng_live_... (ou deixe em branco para usar o do localStorage)",
    nbTokenReady: "● Token pronto",
    nbNoToken: "⚠ Sem token",
    nbNewCellBtn: "+ Nova Célula",
    nbRunningAll: "Executando...",
    nbRunAllBtn: "▶▶ Executar Todas",
    nbClearResultsBtn: "Limpar resultados",
    nbCellSingular: "célula",
    nbCellPlural: "células",
    nbErrorWord: "erro",
    nbFooterPrefix: "Todas as chamadas vão para",
    nbFooterMid: "com seu token Bearer.",
    nbFooterSuffix: "copia o comando equivalente para o terminal.",
  },
  en: {
    navKapua: "Kuapoã",
    navVisuals: "Visual Representations",
    navData: "Data",
    navApplications: "Applications",
    navNist: "NIST Test",
    navDeveloper: "Developer",
    navSettings: "⚙ Settings",

    statusOnline: "ONLINE",
    statusOffline: "OFFLINE",
    effectiveOrigin: "effective origin",
    notVerified: "(not verified)",
    buffer: "Buffer",
    generated: "Generated",
    consumed: "Consumed",
    precollectedRemainingLabel: "Pre-collected",
    remainingOf: "remaining of",
    sourceUnavailableFallback: "Source unavailable — fallback active",
    latency: "Latency",
    sourceRemote: "Remote (SP)",
    sourceFpga: "FPGA (Hardware)",
    sourcePrecollected: "Pre-collected",
    originUnavailable: "unavailable",
    originUnknown: "unknown",

    fbExhausted: "⚠ PRE-COLLECTED BUFFER EXHAUSTED",
    fbDemoMode: "DEMO MODE — PRE-COLLECTED DATA",
    fbBytesRemaining: "bytes remaining",
    fbAlmostExhausted: " (almost exhausted)",
    fbProvenance: "Provenance",
    fbNotRegistered: "not registered",
    fbNotLiveMeasure: "— not a live hardware measurement",
    fbKeyGenBlocked: "Operational key/seed generation blocked on this source",
    fbReuseWarningPrefix: "This reuses the same",
    fbReuseWarningSuffix: "bytes from the start — it does not generate a new sample.",
    fbConfirmRestart: "Confirm restart",
    fbCancel: "Cancel",
    fbRestartDemo: "Restart demo",

    footerConnectedTitle: "Connected to hardware:",
    footerConnectedPrefix: "The QRNG data in this demo comes directly from the source",
    footerConnectedSuffix: ". Entropy is generated by measurements of real quantum phenomena, not by deterministic algorithms.",
    footerOfflineTitle: "Offline mode:",
    footerOfflinePrefix: "The QRNG backend is unavailable. The QRNG data shown is from a",
    footerSamplePrecollected: "pre-collected sample",
    footerOfflineSuffix: "(10,000 bytes from the Red Pitaya). Although this is genuine quantum data, it is not being generated in real time. Connect to the backend for live data.",
    footerDevelopedBy: "Developed by DOBSLIT",

    kc0Name: "Quantum Entropy Source",
    kc0Desc: "The source of randomness comes from a physical quantum process. The captured signal carries unpredictable fluctuations that are not generated by a deterministic algorithm.",
    kc0Badge: "Physical entropy",
    kc1Name: "Analog-to-Digital Conversion",
    kc1Desc: "The physical signal is converted into digital data by an acquisition stage. This step turns quantum noise into digital samples that can be processed.",
    kc1Badge: "Sampling",
    kc2Name: "FPGA / Hardware Processing",
    kc2Desc: "The FPGA performs capture and initial processing of the data, enabling low latency and a continuous stream of random bytes.",
    kc2Badge: "Hardware",
    kc3Name: "Entropy Extraction",
    kc3Desc: "Post-processing removes bias and organizes the bits to produce a sequence suitable for cryptographic applications, simulations, and statistical tests.",
    kc3Badge: "Post-processing",
    kc4Name: "Data Buffer",
    kc4Desc: "Generated bytes are stored in a buffer for consumption by applications, APIs, and system interfaces.",
    kc4Badge: "Buffer",
    kc5Name: "QRNG API",
    kc5Desc: "The API makes random data available for external applications, downloads, key generation, raffles, simulations, and tests.",
    kc5Badge: "Integration",
    kc6Name: "Statistical Validation",
    kc6Desc: "The system can run statistical analyses and NIST tests to assess the quality of the generated data.",
    kc6Badge: "NIST test",
    kc7Name: "Applications",
    kc7Desc: "Random numbers can be used in cryptography, authentication, Monte Carlo methods, AI, optimization, games, education, and research.",
    kc7Badge: "Practical use",
    kf0Title: "QRNG Source / FPGA",
    kf0Desc: "Entropy generated by quantum phenomena in dedicated FPGA hardware.",
    kf1Title: "Physical Entropy",
    kf1Desc: "Fundamentally unpredictable randomness, not algorithms.",
    kf2Title: "Number Generation",
    kf2Desc: "Random numbers and bytes with proven uniform distribution.",
    kf3Title: "Raw Data Download",
    kf3Desc: "Export quantum bytes for use in simulations, research, and analysis.",
    kf4Title: "NIST Statistical Tests",
    kf4Desc: "Entropy validation via the SP 800-90B suite with detailed results.",
    kapuaStepLabel: "Step",
    kapuaOfLabel: "of",
    kapuaPrev: "◀ Previous",
    kapuaNext: "Next ▶",
    kapuaStopFlow: "⏹ Stop",
    kapuaPlayFlow: "▶ View full flow",
    kapuaStatusOnline: "● ONLINE",
    kapuaStatusChecking: "○ CHECKING",
    kapuaStatusFallback: "◐ FALLBACK",
    kapuaStatusDegraded: "◐ DEGRADED",
    kapuaStatusOffline: "○ OFFLINE",
    kapuaSourceDefault: "Kuapoã QRNG",
    kapuaSourceFpga: "FPGA/Hardware",
    kapuaSourceFallbackInternal: "Internal fallback",
    kapuaSubtitle: "Quantum Random Number Generator",
    kapuaDescP: "Kuapoã is Dobslit's quantum random number generation system. It uses a physical quantum source, hardware acquisition, and dedicated processing to generate real entropy for cryptography, simulations, authentication, research, and statistical tests.",
    kapuaGenerating: "⏳ Generating...",
    kapuaGenerateBtn: "🎲 Generate random number",
    kapuaDownloading: "⬇ Downloading...",
    kapuaDownloadBtn: "⬇ Download QRNG data",
    kapuaExploreBtn: "🔍 Explore components",
    kapuaRandomNumberLabel: "RANDOM NUMBER · Source:",
    kapuaDlErrorPrecollected: "The pre-collected source has only 10,000 bytes. Use the Data tab to export up to 10 KB, or select Remote / FPGA for the 1 MiB download.",
    kapuaDlErrorOffline: "QRNG backend offline or unavailable. Go to the Data tab for more options.",
    kapuaExploreLabel: "EXPLORE:",
    kapuaNavDataQrng: "QRNG Data",
    kapuaSvgNistLabel: "NIST Tests",
    kapuaSvgAppsLabel: "Applications",

    dpNoiseQ: "Q. Noise",
    dpEsteDemo: "This Demo",
    dpFotons: "Photons",
    dpOffline: "offline",
    dpSource: "Source",
    statsEntropy: "Entropy",

    qvGalaxy: "Galaxy",
    qvMandala: "Mandala",
    qvCracker: "LCG Cracker",
    qvMtClone: "MT19937 Clone",
    qvSonification: "Sonification",
    qvMathRandomExhausted: "Math.random() — pre-collected exhausted",
    qvMathRandomNetError: "Math.random() — network error",
    qvAboutExperiment: "About this experiment",
    qvSpeed: "Speed",
    qvDisableSound: "Disable sound",
    qvEnableSound: "Enable sound",
    qvVolume: "Volume",
    qvEnablePrng: "Enable PRNG",
    qvMutePrng: "Mute PRNG",
    qvEnableQrng: "Enable QRNG",
    qvMuteQrng: "Mute QRNG",
    qvReset: "Restart",
    qvBytes: "bytes",
    qvFps: "fps",

    vzCoverage: "Coverage",
    vzCollectingOutputs: "COLLECTING OUTPUTS",
    vzInternalState: "INTERNAL STATE (624 32-BIT WORDS)",
    vzCloned: "CLONED!",
    vzPrediction: "PREDICTION",
    vzMt19937Cloned: "MT19937 CLONED",
    vzCloneFailed: "CLONE FAILED",
    vzExperimentDone: "EXPERIMENT FINISHED",
    vzAccuracy: "ACCURACY",
    vzCorrectPredictions: "correct predictions",
    vzObservation: "OBSERVATION",
    vzBreakingLcg: "CRACKING THE LCG...",
    vzRealtimePrediction: "REAL-TIME PREDICTION",
    vzPhase: "PHASE",
    vzLcgCracked: "LCG CRACKED",
    vzUnpredictable: "UNPREDICTABLE",
    vzSonificationTitle: "SONIFICATION — PENTATONIC SCALE",

    asSamples: "Samples",
    asGenerating: "Generating...",
    asGenerate: "Generate",
    asDistribution: "Distribution",
    asBits64: "Bits (64 samples)",

    spParticles: "Particles",
    spStop: "Stop",
    spStart: "Start Stream",
    spUnknownError: "Unknown error",
    spReadyRealtime: "Ready to visualize quantum bytes in real time",
    spUnavailablePrecollected: "Stream unavailable with pre-collected data",
    spBackendOfflineStream: "Backend offline — stream unavailable",
    spWaitingHardware: "Waiting for data from the QRNG hardware...",
    spDisconnected: "Disconnected",
    spReconnect: "Reconnect",
    spClickToStart: "Click \"Start Stream\" to visualize",
    spNoStreamPrecollected: "No stream in pre-collected mode",
    spBackendOffline: "Backend offline",

    visTabInteractive: "Interactive Visualizations",
    visTabAnalysis: "Statistical Analysis",

    dsSourceTitle: "QRNG Source",
    dsPrecollectedActivePrefix: "Pre-collected source active.",
    dsPrecollectedActiveSuffix: "real QRNG bytes available locally.",
    dsDegradedWaiting: "Backend connected, but the entropy buffer is empty. Waiting for the FPGA to refill...",
    dsOnlineReady: "QRNG backend online. Data ready for export.",
    dsOfflineMsg: "QRNG backend offline. Cannot generate real data right now.",
    dsLatency: "latency",
    dsSourceLabel: "source",
    dsBuffer: "buffer",
    dsExportModeTitle: "Export Mode",
    dsModeRaw: "Raw Binary",
    dsModeHex: "Hexadecimal",
    dsModeUint8: "Decimal / uint8",
    dsModeRange: "Custom Range",
    dsModeMontecarlo: "Monte Carlo",
    dsDescRaw: "Exports raw QRNG bytes (.bin). Each byte is 8 bits wide; the real min-entropy per byte is estimated by the NIST SP 800-90B suite (NIST Test tab), never assumed automatically.",
    dsDescHex: "Converts QRNG bytes to hexadecimal representation. Useful for cryptography and debugging.",
    dsDescUint8: "Exports each byte as an integer 0–255 (uint8). Handy for ML, datasets, and statistical analysis.",
    dsDescRange: "Generates integers in an arbitrary [min, max] range. Uses rejection sampling (uint32) to eliminate bias.",
    dsDescMontecarlo: "Generates floats in [0, 1) from QRNG uint32 ÷ 2³². Resolution ≈ 2.3×10⁻¹⁰. Ideal for simulations.",
    dsConfigTitle: "Settings",
    dsSize: "Size:",
    dsCustomBytes: "Custom (bytes):",
    dsSeparator: "Separator:",
    dsBytesPerLine: "Bytes per line:",
    dsFile: "File:",
    dsMin: "Minimum:",
    dsMax: "Maximum:",
    dsQuantity: "Quantity:",
    dsApply: "Apply",
    dsRawFileInfo: "Pure binary format (.bin). File of {size} = {bytes} bytes.",
    dsSepContinuous: "continuous",
    dsSepSpaces: "spaces",
    dsSepPerLine: "per line",
    dsHexInfoArrow: "hex chars",
    dsHexInfoSpaces: "spaces",
    dsUint8Info: "integers in the 0–255 range, generated from raw QRNG bytes.",
    dsAllowRepeats: "Allow repeats",
    dsSortResult: "Sort result",
    dsRangeInvalidCount: "Invalid quantity for no-repeat mode: range [{min}–{max}] has only {n} values.",
    dsRangeGeneratesPrefix: "Generates",
    dsRangeGeneratesMid: "number(s) in the range",
    dsRangeGeneratesSuffix: "Range: {n} values.",
    dsRangeFloyd: "Floyd's F2 algorithm (no repeats, no bias).",
    dsRangeRejection: "uint32 rejection sampling (no bias).",
    dsMcInfo: "Each QRNG uint32 is mapped to [0, 1) via n÷2³². Precision of 15 decimal places. Consumes {n} QRNG bytes.",
    dsQuickAppsTitle: "Quick Applications",
    dsPreset0Label: "Byte Array",
    dsPreset0Desc: "uint8 · 0–255 · 1 KB",
    dsPreset1Label: "Lottery 6/60",
    dsPreset1Desc: "6 num · 1–60 · no rep.",
    dsPreset2Label: "Die (1d6)",
    dsPreset2Desc: "1 number · 1–6",
    dsPreset3Label: "Monte Carlo",
    dsPreset3Desc: "1000 floats · [0, 1)",
    dsPreset4Label: "AI / Dataset",
    dsPreset4Desc: "uint8 · 4 KB · JSON",
    dsPreset5Label: "ID Draw",
    dsPreset5Desc: "no rep. · free range",
    dsPreviewTitle: "Preview and Download",
    dsGeneratingBtn: "⏳ Generating...",
    dsGeneratePreviewBtn: "Generate preview",
    dsDownloadBtn: "↓ Download file",
    dsCopiedBtn: "✓ Copied!",
    dsCopyBtn: "Copy",
    dsClearBtn: "Clear",
    dsPreviewFirst32Hex: "First 32 bytes (hex):",
    dsPreviewFirst64: "First 64 bytes (sep: {sep}):",
    dsPreviewFirst32Of: "First 32 of {n} values:",
    dsPreviewNumbersGenerated: "{n} number(s) generated [{min}–{max}]:",
    dsPreviewMcPoints: "{n} Monte Carlo points [0, 1):",
    dsStatMin: "min",
    dsStatMax: "max",
    dsStatMean: "mean",
    dsStatBytesQrng: "QRNG bytes",
    dsLatencyApi: "API latency",
    dsFileLabel: "file",
    dsSuccessMsg: "✓ File generated successfully using real QRNG entropy.",
    dsConsumedBytes: "{n} QRNG bytes were consumed.",
    dsIdleHintPrefix: "Set the mode above and click",
    dsIdleHintSuffix: "to preview and download QRNG data.",
    dsValidatePrecollectedExceeded: "Pre-collected source: only {remaining} of {total} bytes remain in this session. Reduce the size/quantity, use \"Restart demo\" in the banner above, or switch to a live QRNG source.",
    dsValidateInvalidSize: "Invalid size. Use between 1 and {max}.",
    dsValidateRangeInvalid: "Invalid range: the maximum must be ≥ the minimum.",
    dsValidateMinQty: "Quantity must be at least 1.",
    dsValidateMaxQty: "Maximum quantity is 100,000.",
    dsValidateNoRepeatInvalid: "Invalid quantity for no-repeat mode: range [{min}–{max}] has only {n} distinct values.",
    dsValidateMcQty: "Quantity must be between 1 and 100,000.",
    dsGenerateError: "Error generating QRNG data. Check your connection.",
    dsInsufficientBuffer: "Insufficient QRNG buffer. Try reducing the quantity.",

    apSourceBadgeDefault: "⚛ Kuapoã QRNG",
    apFunctional: "Functional",
    apCopied: "Copied!",
    apCopy: "Copy",
    apReqId: "id",
    apOperationalDisabled: "OPERATIONAL GENERATION DISABLED — statistical validation of the source (restart campaign, SP 800-90B health tests) still pending.",
    apKeyTitle: "🔑 Generate Quantum Key",
    apKeyDesc: "Generate cryptographic keys and seeds from physical entropy provided by Kuapoã.",
    apGenerating: "Generating...",
    apKeyGenerateBtn: "Generate quantum key",
    apKeyBlockedMsg: "Operational key generation is temporarily disabled — the QRNG source is still under statistical validation (restart campaign and SP 800-90B health tests pending). See technical documentation.",
    apKeyPlaceholder: "Select a size and click Generate...",
    apSeedTitle: "🧠 Quantum Seed for AI",
    apSeedDesc: "AI models use randomness for weight initialization, dataset splitting, and experiments. Kuapoã provides seeds based on physical entropy for more robust, reproducible experiments.",
    apSeedGenerateBtn: "Generate AI seed",
    apSeedBlockedMsg: "Operational seed generation is temporarily disabled — the QRNG source is still under statistical validation (restart campaign and SP 800-90B health tests pending). See technical documentation.",
    apSeedUint32Label: "SEED UINT32",
    apSeedUint64Label: "SEED UINT64",
    apUsageExamples: "USAGE EXAMPLES",
    apCopyUint32: "Copy uint32",
    apCopyUint64: "Copy uint64",
    apMcTitle: "π Quantum Monte Carlo",
    apMcDesc: "Estimate π using points generated from quantum entropy and visualize the statistical behavior of the sampling. Each point uses 8 bytes from Kuapoã.",
    apMcCalculating: "Calculating...",
    apMcEstimateBtn: "Estimate π with {n} points",
    apMcRealPi: "real π",
    apMcErrorLabel: "Error",
    apMcInsideTotal: "{inside} inside / {total} total",
    apRaffleMinParticipants: "Enter at least 2 participants.",
    apRaffleTitle: "🎫 Auditable Raffle",
    apRaffleDesc: "Run auditable raffles using QRNG bytes, with timestamp, source, and receipt logging. Uses rejection sampling to avoid modulo bias.",
    apRaffleSortingBtn: "Drawing...",
    apRaffleDrawBtn: "Draw",
    apWinnerLabel: "WINNER",
    apRaffleRankOf: "#{idx} of {total} participants",
    apVoucherLabel: "RECEIPT",
    apCopyVoucher: "Copy receipt",
    apVoucherTemplate: "Kuapoã/Dobslit Raffle | Winner: {winner} | Participants: {total} | Timestamp: {ts} | Source: {source} | Bytes: {bytes}... | Req: {req}",
    apGamesTitle: "🎲 Games and Education",
    apGamesDesc: "Try a coin and a die powered by quantum entropy. Each result uses bytes from the Kuapoã/backend.",
    apCoinTitle: "Quantum Coin",
    apHeads: "HEADS",
    apTails: "TAILS",
    apFlipCoinBtn: "Flip coin",
    apDiceTitle: "Quantum Die",
    apRollDiceBtn: "Roll die",
    apWalkTitle: "🚶 Quantum Random Walk",
    apWalkDesc: "Each step uses 2 bits from Kuapoã: 00=up, 01=down, 10=left, 11=right. Green = start · Red = final position.",
    apStepsWord: "steps",
    apWalkingBtn: "Walking...",
    apStartWalkBtn: "Start walk ({steps} steps)",
    apFinalPosition: "Final position",
    apOptimTitle: "📈 Stochastic Optimization",
    apOptimDesc: "Stochastic optimization algorithms depend on good sources of randomness. Here we search for the maximum of f(x) = sin(x) + cos(2x) on [0, 2π] via random quantum sampling.",
    apSamplesWord: "samples",
    apOptimizingBtn: "Optimizing...",
    apFindMaxBtn: "Find maximum with {n} QRNG samples",
    apOptimalX: "optimal x (rad)",
    apMaxFx: "max f(x)",
    apBestSampleNum: "Best sample #",
    apMainTitle: "Kuapoã Applications",
    apMainDesc: "Explore practical demonstrations of Kuapoã's quantum randomness. All applications use bytes supplied by Dobslit's QRNG/backend — including the internal fallback when the FPGA is unavailable. No application uses external randomness services.",
    apDemosCount: "7 demos",
    apNoExternalServices: "No external services",

    nistPassed: "Passed",
    nistFailed: "Failed",
    nistOriginPeriodicLive: "Periodic live source measurement",
    nistOriginLive: "Live capture",
    nistOriginHistorical: "Historical file",
    nistOriginUpload: "Manual upload",
    nistOriginUnknown: "Unknown",
    nistSyntheticTag: "SYNTHETIC",
    nistTestBoth: "IID + non-IID",
    nistTestIidOnly: "IID only",
    nistTestNonIidOnly: "non-IID only",
    nistFmtAuto: "Auto (detect)",
    nistFmtRaw: "Raw/binary (.bin)",
    nistFmtU32txt: "uint32 text (.txt)",
    nistFmtBits: "Bits 0/1 (.txt)",
    nistJobTitle: "NIST Job",
    nistTabSummary: "Summary",
    nistTabEstimators: "Estimators",
    nistTabFullLog: "Full log",
    nistFileSection: "FILE",
    nistOriginalName: "Original name",
    nistTestTypeLabel: "Test type",
    nistFormatLabel: "Format",
    nistTriggerLabel: "Trigger",
    nistDurationLabel: "Duration",
    nistSha256Label: "Original SHA-256",
    nistIidLabel: "IID",
    nistNonIidLabel: "NON-IID",
    nistHOriginalSymbol: "H_original (per 8-bit symbol)",
    nistLimitingEstimatorOriginal: "↳ limiting estimator (original)",
    nistHBitstringBit: "H_bitstring (per bit)",
    nistLimitingEstimatorBitstring: "↳ limiting estimator (bitstring)",
    nistBitstringConversion: "bitstring→symbol conversion",
    nistHMinNonIid: "h_min_non_iid = min(H_original, 8×H_bitstring)",
    nistLimitingPath: "limiting track",
    nistLimitingEstimator: "limiting estimator (matches h_min)",
    nistIidFailedWarningPrefix: "⚠ IID hypothesis failed → the entropy credit is",
    nistIidFailedWarningSuffix: "bits/8-bit symbol). h_min_iid is NOT used.",
    nistParseIncomplete: "⚠ Incomplete assessment output — some essential field could not be extracted.",
    nistTrackOriginal: "ORIGINAL TRACK (per 8-bit symbol)",
    nistTrackBitstring: "BITSTRING TRACK (per bit)",
    nistBitsPerSymbol: "bits/symbol",
    nistBitsPerBit: "bits/bit",
    nistLimits: "◀ limits",
    nistAwaitingCompletion: "Awaiting completion...",
    nistLogNotAvailable: "Log not yet available.",
    nistLoadingLog: "Loading log...",
    nistServiceDownMsg: "⚠ NIST service unreachable. Check that qrng-nist-api is running on the Recife VM.",
    nistSyntheticBanner: "SYNTHETIC STAGING RESULT — NOT AN SP 800-90B ASSESSMENT",
    nistSyntheticBannerPrefix: "Engine:",
    nistSyntheticBannerSuffix: "The IID / non-IID / min-H fields below are deterministic synthetic values used to test parsing and the interface — they do NOT represent a statistical entropy assessment and do NOT constitute NIST compliance.",
    nistIntegration: "Integration",
    nistEnabled: "Enabled",
    nistDisabled: "Disabled",
    nistEngine: "Engine",
    nistNextAuto: "Next automatic",
    nistNextAutoDisabled: "disabled (no live capture)",
    nistInterval: "Interval",
    nistQueue: "Queue",
    nistJobsWord: "job(s)",
    nistLiveCaptureUnavailablePrefix: "ℹ Live capture unavailable — no controlled live-capture mechanism is configured. No periodic run is scheduled",
    nistLiveCaptureUnavailableSuffix: "the periodic job does not automatically re-evaluate any file. Results below (if any) come from manual upload or a one-off run on a specific file.",
    nistLastResult: "LATEST RESULT",
    nistOriginPrefix: "Origin:",
    nistOriginPeriodicDetail: "Periodic live source measurement — see \"Sample age\" to know how long ago it was captured.",
    nistOriginSpecificDetail: "Assessment of a specific sample, not a continuous measurement of the live stream's current health.",
    nistStaleWarningPrefix: "⚠ STALE SAMPLE — captured",
    nistStaleWarningMid: "ago, longer than the interval between periodic runs",
    nistStaleWarningSuffix: "This result does not reflect the current state of the live source.",
    nistStatusLabel: "Status",
    nistMinHLabel: "min-H non-IID",
    nistFileLabel: "File",
    nistSubmittedAt: "Submitted at",
    nistSampleAge: "Sample age",
    nistTransportOrigin: "Transport / physical origin",
    nistEvaluatedSymbol: "Symbol evaluated by NIST",
    nistPerWord: "word",
    nistConditioned: "conditioned",
    nistNotConditioned: "no conditioning",
    nistRunNowTitle: "Run test now",
    nistRunNowDescPrefix: "Tests the most recent file in",
    nistRunNowDescSuffix: "(≥ 1 MB).",
    nistCreatingJob: "Creating job...",
    nistAwaitingJob: "Awaiting job...",
    nistRunNowBtn: "▶ Run test now",
    nistJobRunningPrefix: "● Job",
    nistJobRunningSuffix: "running...",
    nistUploadTitle: "Upload + test",
    nistUploadDescPrefix: "Upload a",
    nistUploadDescSuffix: "file. Minimum 1 MB.",
    nistSending: "Uploading...",
    nistUploadBtn: "⬆ Upload and test",
    nistJobHistory: "Job history",
    nistRefreshBtn: "↺ Refresh",
    nistNoJobs: "No jobs recorded yet.",
    nistThDate: "Date/time",
    nistThTrigger: "Trigger",
    nistThFile: "File",
    nistThTest: "Test",
    nistThStatus: "Status",
    nistThIid: "IID",
    nistThMinH: "min-H non-IID",
    nistThDuration: "Duration",
    nistViewBtn: "View",
    nistDaysWord: "days",
    nistCreateJobError: "Error creating job",
    nistUploadError: "Upload error",

    devEndpointsAvailable: "Available endpoints",
    devEpRandomDesc: "Random bytes (max. 1 MiB)",
    devEpHealthDesc: "Upstream QRNG status",
    devEpTokenDesc: "Your token information",
    devEpUsageDesc: "Usage statistics",
    devEpRequestsDesc: "Call history",
    devEpRotateDesc: "Regenerate token",
    devEpRevokeDesc: "Revoke token",
    devExRandomHex: "Generate random bytes (hex)",
    devExRandomBase64: "Generate random bytes (base64)",
    devExHealth: "QRNG status",
    devExUsage: "Query token usage",
    devUsageExamplesTitle: "Usage examples",
    devAuthTitle: "Authentication:",
    devAuthDescPrefix: "Machine-to-machine calls use the header",
    devAuthDescSuffix: "The API token never expires, but it can be regenerated or revoked in the Token tab.",
    devTokenLoadError: "Could not load token information.",
    devTokenServerDown: "Token server unavailable.",
    devTabUsage: "Usage",
    devTabCalls: "Calls",
    devCheckingSession: "Checking session...",
    devAreaTitle: "QRNG API — Developer Area",
    devFpgaOnline: "● FPGA Online",
    devFpgaOffline: "● FPGA Offline",
    devFpgaChecking: "● FPGA …",
    devUptime24h: "24h uptime",
    devLogout: "Log out",
    devQuotaCritical: "Quota almost exhausted — {n}/{m} req today ({pct}%). Resets at midnight UTC.",
    devQuotaWarning: "Warning: {pct}% of the daily quota used ({n}/{m} req).",
    devLoadingGeneric: "Loading...",
    devLoadingStats: "Loading statistics...",
    devLoadingCalls: "Loading calls...",
    devGenerateTokenFirst: "Generate a token first in the Token tab.",

    authPasswordMismatch: "Passwords do not match.",
    authPasswordTooShort: "Password must be at least 8 characters.",
    authInvalidCredentials: "Incorrect email or password.",
    authEmailTaken: "This email is already registered.",
    authMissingFields: "Please fill in email and password.",
    authUnknownError: "Unknown error.",
    authConnectionError: "Could not connect to the server.",
    authLoginPrompt: "Log in to access your token and usage logs.",
    authRegisterPrompt: "Create an account to get access to the quantum randomness API.",
    authLogin: "Log in",
    authCreateAccount: "Create account",
    authEmailPlaceholder: "Email",
    authPasswordPlaceholder: "Password",
    authConfirmPasswordPlaceholder: "Confirm password",
    authWait: "Please wait...",
    authNoAccount: "No account?",
    authSignUp: "Sign up",

    tcMyApiToken: "My API Token",
    tcActive: "● Active",
    tcRevoked: "● Revoked",
    tcSaveNowWarning: "Save your token now — it will not be shown again after you leave this page.",
    tcGenerateTitle: "Generate your access token",
    tcGenerateDescPrefix: "Each account has a unique API access token. Use it in the header",
    tcGenerateDescSuffix: "on every call.",
    tcQuota: "1,000 req/day",
    tcQuotaDesc: "Daily quota for authenticated calls",
    tcMaxSize: "Up to 1 MiB per req",
    tcMaxSizeDesc: "1,048,576 bytes — hex, base64, or uint8 formats",
    tcPermanentToken: "Permanent token",
    tcPermanentTokenDesc: "Never expires; can be regenerated or revoked at any time",
    tcLogsStats: "Logs and statistics",
    tcLogsStatsDesc: "Full history of calls and aggregate usage",
    tcGenerating: "Generating...",
    tcGenerateBtn: "Generate Token",
    tcHide: "Hide",
    tcShow: "Show",
    tcRegenerating: "Please wait...",
    tcRegenerateBtn: "Regenerate",
    tcRevokeBtn: "Revoke",
    tcGenerateNewBtn: "Generate New Token",
    tcCreatedAt: "Created",
    tcLastUsedAt: "Last used",
    tcName: "Name",
    tcCreateError: "Error creating token.",
    tcRotateError: "Error regenerating token.",
    tcRevokeError: "Error revoking token.",
    tcConnectionError: "Could not connect to the server.",
    tcRotateConfirm: "Regenerating the token will invalidate the current one. Continue?",
    tcRevokeConfirm: "Revoking the token will permanently disable access. Continue?",

    ucTitle: "Token Usage",
    ucRequestsToday: "Requests today",
    ucBytesToday: "Bytes today",
    ucRequests7d: "Requests 7d",
    ucRequests30d: "Requests 30d",
    ucDailyQuotaRequests: "Daily quota — requests",
    ucDailyQuotaBytes: "Daily quota — bytes",
    ucRemainingToday: "remaining today",
    ucLimitPerReq: "Limit per req",
    ucRemainingTodayFull: "Remaining today",
    ucLastUsedAt: "Last used",

    rltRecentCalls: "Recent Calls",
    rltNoCallsYet: "No calls recorded yet.",
    rltExporting: "Exporting...",
    rltExportCsv: "Export CSV",
    rltFormat: "format",
    rltTime: "time",
    rltDate: "date",

    adminPanelTitle: "Admin Panel",
    adminRefresh: "Refresh",
    adminTabTokens: "Tokens",
    adminTabUsers: "Users",
    adminThEmail: "email",
    adminThQuotaDay: "quota/day",
    adminThReqToday: "req today",
    adminThCreated: "created",
    adminThActions: "actions",
    adminNoTokens: "No tokens found.",
    adminRevokeTokenConfirm: "Revoke this token?",
    adminThRole: "role",
    adminThRegisteredAt: "registered on",
    adminNoUsers: "No users found.",

    nbEpRandom: "GET /v1/random — Random bytes",
    nbEpHealth: "GET /v1/health — QRNG status",
    nbEpMeToken: "GET /v1/me/token — Token information",
    nbEpMeUsage: "GET /v1/me/usage — Usage statistics",
    nbEpMeRequests: "GET /v1/me/requests — Call history",
    nbParamFormat: "Format",
    nbParamLimit: "Limit",
    nbRunning: "Running...",
    nbErrorMs: "Error",
    nbNotExecuted: "Not executed",
    nbCopyAsCurl: "Copy as curl",
    nbRunBtn: "▶ Run",
    nbRemoveCellTitle: "Remove cell",
    nbPressRunToExecute: "Press ▶ Run to execute",
    nbTokenLabel: "Token:",
    nbTokenPlaceholder: "dobslit_qrng_live_... (or leave blank to use the one in localStorage)",
    nbTokenReady: "● Token ready",
    nbNoToken: "⚠ No token",
    nbNewCellBtn: "+ New Cell",
    nbRunningAll: "Running...",
    nbRunAllBtn: "▶▶ Run All",
    nbClearResultsBtn: "Clear results",
    nbCellSingular: "cell",
    nbCellPlural: "cells",
    nbErrorWord: "error",
    nbFooterPrefix: "All calls go to",
    nbFooterMid: "with your Bearer token.",
    nbFooterSuffix: "copies the equivalent command to the terminal.",
  },
};

export const SOURCE_KEY_MAP = {
  remote: "sourceRemote",
  fpga: "sourceFpga",
  "pre-collected": "sourcePrecollected",
};

export const LanguageContext = createContext(null);

function loadLang() {
  try {
    const saved = localStorage.getItem(STORAGE_KEY);
    if (saved === "pt" || saved === "en") return saved;
  } catch { /* localStorage indisponível (modo privado etc.) */ }
  return "pt";
}

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(loadLang);

  const setLang = (newLang) => {
    setLangState(newLang);
    try { localStorage.setItem(STORAGE_KEY, newLang); } catch { /* best-effort */ }
  };

  // `params` opcional interpola {placeholder} na string traduzida --
  // ex.: t("dsValidateInvalidSize", { max: "1 MiB" }).
  const t = (key, params) => {
    const raw = translations[lang][key] ?? translations.pt[key] ?? key;
    if (!params) return raw;
    return raw.replace(/\{(\w+)\}/g, (m, name) => (name in params ? String(params[name]) : m));
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within a LanguageProvider");
  return ctx;
}
