import { createContext, useContext, useState } from "react";

const STORAGE_KEY = "qrng-lang";

// Dicionário PT/EN do site, mesmo padrão do portal Bongo (front/src/context/language).
const translations = {
  pt: {
    // ── Navegação principal (SectionNav) ──
    navKapua: "Kuapoã",
    navVisuals: "Representações Visuais",
    navData: "Dados",
    navApplications: "Aplicações",
    navNist: "Teste NIST",
    navDeveloper: "Desenvolvedor",
    navSettings: "⚙ Configurações",

    // ── HardwareStatusBar ──
    statusOnline: "ONLINE",
    statusOffline: "OFFLINE",
    effectiveOrigin: "origem efetiva",
    notVerified: "(não verificada)",
    buffer: "Buffer",
    generated: "Gerado",
    consumed: "Consumido",
    precollectedRemainingLabel: "Pré-coletado",
    remainingOf: "restantes de",
    sourceUnavailableFallback: "Fonte indisponível — fallback ativo",
    latency: "Latência",
    sourceRemote: "Remota (SP)",
    sourceFpga: "FPGA (Hardware)",
    sourcePrecollected: "Pré-coletado",
    originUnavailable: "indisponível",
    originUnknown: "desconhecida",

    // ── FallbackBanner ──
    fbExhausted: "⚠ BUFFER PRÉ-COLETADO ESGOTADO",
    fbDemoMode: "MODO DEMONSTRAÇÃO — DADOS PRÉ-COLETADOS",
    fbBytesRemaining: "bytes restantes",
    fbAlmostExhausted: " (quase esgotado)",
    fbProvenance: "Proveniência",
    fbNotRegistered: "não registrada",
    fbNotLiveMeasure: "— não é uma medida ao vivo do hardware",
    fbKeyGenBlocked: "Geração de chaves/seed operacional bloqueada nesta fonte",
    fbReuseWarningPrefix: "Isso reaproveita os mesmos",
    fbReuseWarningSuffix: "bytes desde o início — não gera uma amostra nova.",
    fbConfirmRestart: "Confirmar reinício",
    fbCancel: "Cancelar",
    fbRestartDemo: "Reiniciar demonstração",

    // ── Footer ──
    footerConnectedTitle: "Conectado ao hardware:",
    footerConnectedPrefix: "Os dados QRNG nesta demo vêm diretamente da fonte",
    footerConnectedSuffix: "A entropia é gerada por medições de fenômenos quânticos reais, não por algoritmos determinísticos.",
    footerOfflineTitle: "Modo offline:",
    footerOfflinePrefix: "O backend QRNG está indisponível. Os dados QRNG exibidos são de uma",
    footerSamplePrecollected: "amostra pré-coletada",
    footerOfflineSuffix: "(10.000 bytes do Red Pitaya). Embora sejam dados quânticos genúinos, não estão sendo gerados em tempo real. Conecte ao backend para dados ao vivo.",
    footerDevelopedBy: "Desenvolvido por DOBSLIT",

    // ── KapuaSection (página inicial) ──
    kc0Name: "Fonte de Entropia Quântica",
    kc0Desc: "A origem da aleatoriedade vem de um processo físico quântico. O sinal capturado carrega flutuações imprevisíveis que não são geradas por algoritmo determinístico.",
    kc0Badge: "Entropia física",
    kc1Name: "Conversão Analógico-Digital",
    kc1Desc: "O sinal físico é convertido para dados digitais por um estágio de aquisição. Essa etapa transforma o ruído quântico em amostras digitais que podem ser processadas.",
    kc1Badge: "Amostragem",
    kc2Name: "FPGA / Processamento em Hardware",
    kc2Desc: "A FPGA realiza a captura e o processamento inicial dos dados, permitindo baixa latência e fluxo contínuo de bytes aleatórios.",
    kc2Badge: "Hardware",
    kc3Name: "Extração de Entropia",
    kc3Desc: "O pós-processamento remove vieses e organiza os bits para produzir uma sequência adequada para aplicações criptográficas, simulações e testes estatísticos.",
    kc3Badge: "Pós-processamento",
    kc4Name: "Buffer de Dados",
    kc4Desc: "Os bytes gerados são armazenados em um buffer para consumo pelas aplicações, APIs e interfaces do sistema.",
    kc4Badge: "Buffer",
    kc5Name: "API QRNG",
    kc5Desc: "A API disponibiliza os dados aleatórios para aplicações externas, download, geração de chaves, sorteios, simulações e testes.",
    kc5Badge: "Integração",
    kc6Name: "Validação Estatística",
    kc6Desc: "O sistema pode executar análises estatísticas e testes NIST para avaliar a qualidade dos dados gerados.",
    kc6Badge: "Teste NIST",
    kc7Name: "Aplicações",
    kc7Desc: "Os números aleatórios podem ser usados em criptografia, autenticação, Monte Carlo, IA, otimização, jogos, educação e pesquisa.",
    kc7Badge: "Uso prático",
    kf0Title: "Fonte QRNG / FPGA",
    kf0Desc: "Entropia gerada por fenômenos quânticos em hardware FPGA dedicado.",
    kf1Title: "Entropia Física",
    kf1Desc: "Aleatoriedade fundamentalmente imprevisível, não algoritmos.",
    kf2Title: "Geração de Números",
    kf2Desc: "Números e bytes aleatórios com distribuição uniforme comprovada.",
    kf3Title: "Download de Dados Brutos",
    kf3Desc: "Exporte bytes quânticos para uso em simulações, pesquisa e análise.",
    kf4Title: "Testes Estatísticos NIST",
    kf4Desc: "Validação de entropia via suíte SP 800-90B com resultados detalhados.",
    kapuaStepLabel: "Etapa",
    kapuaOfLabel: "de",
    kapuaPrev: "◀ Anterior",
    kapuaNext: "Próximo ▶",
    kapuaStopFlow: "⏹ Parar",
    kapuaPlayFlow: "▶ Ver fluxo completo",
    kapuaStatusOnline: "● ONLINE",
    kapuaStatusChecking: "○ VERIFICANDO",
    kapuaStatusFallback: "◐ FALLBACK",
    kapuaStatusDegraded: "◐ DEGRADADO",
    kapuaStatusOffline: "○ OFFLINE",
    kapuaSourceDefault: "Kuapoã QRNG",
    kapuaSourceFpga: "FPGA/Hardware",
    kapuaSourceFallbackInternal: "Fallback interno",
    kapuaSubtitle: "Gerador Quântico de Números Aleatórios",
    kapuaDescP: "O Kuapoã é o sistema de geração de números aleatórios quânticos da Dobslit. Ele utiliza uma fonte física quântica, aquisição em hardware e processamento dedicado para gerar entropia real para criptografia, simulações, autenticação, pesquisa e testes estatísticos.",
    kapuaGenerating: "⏳ Gerando...",
    kapuaGenerateBtn: "🎲 Gerar número aleatório",
    kapuaDownloading: "⬇ Baixando...",
    kapuaDownloadBtn: "⬇ Baixar dados QRNG",
    kapuaExploreBtn: "🔍 Explorar componentes",
    kapuaRandomNumberLabel: "NÚMERO ALEATÓRIO · Fonte:",
    kapuaDlErrorPrecollected: "Fonte pré-coletada tem apenas 10.000 bytes. Use a aba Dados para exportar até 10 KB, ou selecione Remote / FPGA para o download de 1 MiB.",
    kapuaDlErrorOffline: "Backend QRNG offline ou indisponível. Acesse a aba Dados para mais opções.",
    kapuaExploreLabel: "EXPLORAR:",
    kapuaNavDataQrng: "Dados QRNG",
    kapuaSvgNistLabel: "Testes NIST",
    kapuaSvgAppsLabel: "Aplicações",

    // ── DataPipeline / StatsBadges (games) ──
    dpNoiseQ: "Ruido Q.",
    dpEsteDemo: "Este Demo",
    dpFotons: "Fotons",
    dpOffline: "offline",
    dpSource: "Fonte",
    statsEntropy: "Entropia",

    // ── QuantumVisualizer ──
    qvGalaxy: "Galaxia",
    qvMandala: "Mandala",
    qvCracker: "LCG Cracker",
    qvMtClone: "MT19937 Clone",
    qvSonification: "Sonificação",
    qvMathRandomExhausted: "Math.random() — pré-coletado esgotado",
    qvMathRandomNetError: "Math.random() — erro de rede",
    qvAboutExperiment: "Sobre este experimento",
    qvSpeed: "Velocidade",
    qvDisableSound: "Desativar som",
    qvEnableSound: "Ativar som",
    qvVolume: "Volume",
    qvEnablePrng: "Ativar PRNG",
    qvMutePrng: "Mutar PRNG",
    qvEnableQrng: "Ativar QRNG",
    qvMuteQrng: "Mutar QRNG",
    qvReset: "Reiniciar",
    qvBytes: "bytes",
    qvFps: "fps",

    // ── Canvas labels (visualizations/*.js) ──
    vzCoverage: "Cobertura",
    vzCollectingOutputs: "COLETANDO SAIDAS",
    vzInternalState: "ESTADO INTERNO (624 PALAVRAS DE 32 BITS)",
    vzCloned: "CLONADO!",
    vzPrediction: "PREDICAO",
    vzMt19937Cloned: "MT19937 CLONADO",
    vzCloneFailed: "CLONE FALHOU",
    vzExperimentDone: "EXPERIMENTO CONCLUIDO",
    vzAccuracy: "ACURACIA",
    vzCorrectPredictions: "predicoes corretas",
    vzObservation: "OBSERVACAO",
    vzBreakingLcg: "QUEBRANDO O LCG...",
    vzRealtimePrediction: "PREDICAO EM TEMPO REAL",
    vzPhase: "FASE",
    vzLcgCracked: "LCG QUEBRADO",
    vzUnpredictable: "IMPREVISIVEL",
    vzSonificationTitle: "SONIFICACAO — ESCALA PENTATONICA",
  },
  en: {
    navKapua: "Kuapoã",
    navVisuals: "Visual Representations",
    navData: "Data",
    navApplications: "Applications",
    navNist: "NIST Test",
    navDeveloper: "Developer",
    navSettings: "⚙ Settings",

    statusOnline: "ONLINE",
    statusOffline: "OFFLINE",
    effectiveOrigin: "effective origin",
    notVerified: "(not verified)",
    buffer: "Buffer",
    generated: "Generated",
    consumed: "Consumed",
    precollectedRemainingLabel: "Pre-collected",
    remainingOf: "remaining of",
    sourceUnavailableFallback: "Source unavailable — fallback active",
    latency: "Latency",
    sourceRemote: "Remote (SP)",
    sourceFpga: "FPGA (Hardware)",
    sourcePrecollected: "Pre-collected",
    originUnavailable: "unavailable",
    originUnknown: "unknown",

    fbExhausted: "⚠ PRE-COLLECTED BUFFER EXHAUSTED",
    fbDemoMode: "DEMO MODE — PRE-COLLECTED DATA",
    fbBytesRemaining: "bytes remaining",
    fbAlmostExhausted: " (almost exhausted)",
    fbProvenance: "Provenance",
    fbNotRegistered: "not registered",
    fbNotLiveMeasure: "— not a live hardware measurement",
    fbKeyGenBlocked: "Operational key/seed generation blocked on this source",
    fbReuseWarningPrefix: "This reuses the same",
    fbReuseWarningSuffix: "bytes from the start — it does not generate a new sample.",
    fbConfirmRestart: "Confirm restart",
    fbCancel: "Cancel",
    fbRestartDemo: "Restart demo",

    footerConnectedTitle: "Connected to hardware:",
    footerConnectedPrefix: "The QRNG data in this demo comes directly from the source",
    footerConnectedSuffix: ". Entropy is generated by measurements of real quantum phenomena, not by deterministic algorithms.",
    footerOfflineTitle: "Offline mode:",
    footerOfflinePrefix: "The QRNG backend is unavailable. The QRNG data shown is from a",
    footerSamplePrecollected: "pre-collected sample",
    footerOfflineSuffix: "(10,000 bytes from the Red Pitaya). Although this is genuine quantum data, it is not being generated in real time. Connect to the backend for live data.",
    footerDevelopedBy: "Developed by DOBSLIT",

    kc0Name: "Quantum Entropy Source",
    kc0Desc: "The source of randomness comes from a physical quantum process. The captured signal carries unpredictable fluctuations that are not generated by a deterministic algorithm.",
    kc0Badge: "Physical entropy",
    kc1Name: "Analog-to-Digital Conversion",
    kc1Desc: "The physical signal is converted into digital data by an acquisition stage. This step turns quantum noise into digital samples that can be processed.",
    kc1Badge: "Sampling",
    kc2Name: "FPGA / Hardware Processing",
    kc2Desc: "The FPGA performs capture and initial processing of the data, enabling low latency and a continuous stream of random bytes.",
    kc2Badge: "Hardware",
    kc3Name: "Entropy Extraction",
    kc3Desc: "Post-processing removes bias and organizes the bits to produce a sequence suitable for cryptographic applications, simulations, and statistical tests.",
    kc3Badge: "Post-processing",
    kc4Name: "Data Buffer",
    kc4Desc: "Generated bytes are stored in a buffer for consumption by applications, APIs, and system interfaces.",
    kc4Badge: "Buffer",
    kc5Name: "QRNG API",
    kc5Desc: "The API makes random data available for external applications, downloads, key generation, raffles, simulations, and tests.",
    kc5Badge: "Integration",
    kc6Name: "Statistical Validation",
    kc6Desc: "The system can run statistical analyses and NIST tests to assess the quality of the generated data.",
    kc6Badge: "NIST test",
    kc7Name: "Applications",
    kc7Desc: "Random numbers can be used in cryptography, authentication, Monte Carlo methods, AI, optimization, games, education, and research.",
    kc7Badge: "Practical use",
    kf0Title: "QRNG Source / FPGA",
    kf0Desc: "Entropy generated by quantum phenomena in dedicated FPGA hardware.",
    kf1Title: "Physical Entropy",
    kf1Desc: "Fundamentally unpredictable randomness, not algorithms.",
    kf2Title: "Number Generation",
    kf2Desc: "Random numbers and bytes with proven uniform distribution.",
    kf3Title: "Raw Data Download",
    kf3Desc: "Export quantum bytes for use in simulations, research, and analysis.",
    kf4Title: "NIST Statistical Tests",
    kf4Desc: "Entropy validation via the SP 800-90B suite with detailed results.",
    kapuaStepLabel: "Step",
    kapuaOfLabel: "of",
    kapuaPrev: "◀ Previous",
    kapuaNext: "Next ▶",
    kapuaStopFlow: "⏹ Stop",
    kapuaPlayFlow: "▶ View full flow",
    kapuaStatusOnline: "● ONLINE",
    kapuaStatusChecking: "○ CHECKING",
    kapuaStatusFallback: "◐ FALLBACK",
    kapuaStatusDegraded: "◐ DEGRADED",
    kapuaStatusOffline: "○ OFFLINE",
    kapuaSourceDefault: "Kuapoã QRNG",
    kapuaSourceFpga: "FPGA/Hardware",
    kapuaSourceFallbackInternal: "Internal fallback",
    kapuaSubtitle: "Quantum Random Number Generator",
    kapuaDescP: "Kuapoã is Dobslit's quantum random number generation system. It uses a physical quantum source, hardware acquisition, and dedicated processing to generate real entropy for cryptography, simulations, authentication, research, and statistical tests.",
    kapuaGenerating: "⏳ Generating...",
    kapuaGenerateBtn: "🎲 Generate random number",
    kapuaDownloading: "⬇ Downloading...",
    kapuaDownloadBtn: "⬇ Download QRNG data",
    kapuaExploreBtn: "🔍 Explore components",
    kapuaRandomNumberLabel: "RANDOM NUMBER · Source:",
    kapuaDlErrorPrecollected: "The pre-collected source has only 10,000 bytes. Use the Data tab to export up to 10 KB, or select Remote / FPGA for the 1 MiB download.",
    kapuaDlErrorOffline: "QRNG backend offline or unavailable. Go to the Data tab for more options.",
    kapuaExploreLabel: "EXPLORE:",
    kapuaNavDataQrng: "QRNG Data",
    kapuaSvgNistLabel: "NIST Tests",
    kapuaSvgAppsLabel: "Applications",

    dpNoiseQ: "Q. Noise",
    dpEsteDemo: "This Demo",
    dpFotons: "Photons",
    dpOffline: "offline",
    dpSource: "Source",
    statsEntropy: "Entropy",

    qvGalaxy: "Galaxy",
    qvMandala: "Mandala",
    qvCracker: "LCG Cracker",
    qvMtClone: "MT19937 Clone",
    qvSonification: "Sonification",
    qvMathRandomExhausted: "Math.random() — pre-collected exhausted",
    qvMathRandomNetError: "Math.random() — network error",
    qvAboutExperiment: "About this experiment",
    qvSpeed: "Speed",
    qvDisableSound: "Disable sound",
    qvEnableSound: "Enable sound",
    qvVolume: "Volume",
    qvEnablePrng: "Enable PRNG",
    qvMutePrng: "Mute PRNG",
    qvEnableQrng: "Enable QRNG",
    qvMuteQrng: "Mute QRNG",
    qvReset: "Restart",
    qvBytes: "bytes",
    qvFps: "fps",

    vzCoverage: "Coverage",
    vzCollectingOutputs: "COLLECTING OUTPUTS",
    vzInternalState: "INTERNAL STATE (624 32-BIT WORDS)",
    vzCloned: "CLONED!",
    vzPrediction: "PREDICTION",
    vzMt19937Cloned: "MT19937 CLONED",
    vzCloneFailed: "CLONE FAILED",
    vzExperimentDone: "EXPERIMENT FINISHED",
    vzAccuracy: "ACCURACY",
    vzCorrectPredictions: "correct predictions",
    vzObservation: "OBSERVATION",
    vzBreakingLcg: "CRACKING THE LCG...",
    vzRealtimePrediction: "REAL-TIME PREDICTION",
    vzPhase: "PHASE",
    vzLcgCracked: "LCG CRACKED",
    vzUnpredictable: "UNPREDICTABLE",
    vzSonificationTitle: "SONIFICATION — PENTATONIC SCALE",
  },
};

export const SOURCE_KEY_MAP = {
  remote: "sourceRemote",
  fpga: "sourceFpga",
  "pre-collected": "sourcePrecollected",
};

export const LanguageContext = createContext(null);

function loadLang() {
  try {
    const saved = localStorage.getItem(STORAGE_KEY);
    if (saved === "pt" || saved === "en") return saved;
  } catch { /* localStorage indisponível (modo privado etc.) */ }
  return "pt";
}

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(loadLang);

  const setLang = (newLang) => {
    setLangState(newLang);
    try { localStorage.setItem(STORAGE_KEY, newLang); } catch { /* best-effort */ }
  };

  const t = (key) => translations[lang][key] ?? translations.pt[key] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within a LanguageProvider");
  return ctx;
}
